services:
  react-app:
    image: watercubz/mtaai-core.app:latest
    ports:
      - '5173:80'
    env_file:
      - .env
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'
