name: ESLint

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']
  schedule:
    - cron: '39 14 * * 1'

jobs:
  eslint:
    name: Run eslint scanning
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        run: |
          npm install -g pnpm

      - name: Install ESLint
        run: |
          pnpm add eslint@8.10.0
          pnpm add @microsoft/eslint-formatter-sarif@3.1.0

      - name: Run ESLint
        env:
          SARIF_ESLINT_IGNORE_SUPPRESSED: 'true'
        run: |
          npx eslint . \
            --config .eslintrc.js \
            --ext .js,.jsx,.ts,.tsx \
            --format @microsoft/eslint-formatter-sarif \
            --output-file eslint-results.sarif
        continue-on-error: true

      - name: Check if eslint-results.sarif exists
        run: |
          ls -la
          cat eslint-results.sarif || echo "File not found"

      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ./eslint-results.sarif
          wait-for-processing: true
